### PR TITLE
Fix asset-only PR handling by fetching parent file content

### LINKED ISSUE #420: EIP bot should merge asset changes
If the author of EIP-N makes a change the assets in EIP-N, the EIP bot should be able to understand this and merge it. It seems though in PRs like https://github.com/ethereum/ERCs/pull/1289 and https://github.com/ethereum/ERCs/pull/1325. In the second, it actually tags editors to review.

### PR DESCRIPTION
**Pull request by dionysuzx**
Fixes #420 

## Problem

When a PR only touches asset files (e.g. `assets/eip-1234/image.png`), the bot creates a synthetic `EIPS/eip-1234.md` file to run rules against — but without fetching the actual file content. Since there's no frontmatter to parse, `checkAuthors` returns nothing and the bot falls back to a `statuschange` rule, blocking the PR and requiring editor review even when the PR author is an EIP author.

A secondary bug: `split("/")[2]` on `assets/eip-1234/image.png` gives `image.png` instead of `eip-1234`, causing the duplicate-file check to never match.

## Fix

- Fetch the parent EIP/ERC markdown from the default branch via the GitHub API so `checkAuthors` can parse authors from frontmatter
- Fix `split("/")[2]` → `split("/")[1]` to correctly extract the EIP number
- Add 4 tests + a `moduleNameMapper` fix for `.js` → `.ts` resolution in Jest

## Testing

Tested end-to-end on [dionysuzx/EIPs#5](https://github.com/dionysuzx/EIPs/pull/5) — an asset-only PR (`assets/eip-99999/test-run-5.json`) where `EIPS/eip-99999.md` lists `@dionysuzx` as author.

**Unfixed bot** ([run](https://github.com/dionysuzx/EIPs/actions/runs/22679370709)): `statuschange` rule, posted "Requires 1 more reviewers from @mayushii-nyan", PR blocked.

**Fixed bot** ([run](https://github.com/dionysuzx/EIPs/actions/runs/22679426821)): `authors` rule with `pr_approval: true`, matched PR author, enabled auto-merge.

### CODE REVIEW

File: src/rules/assets.ts [hunk 1]
```diff
@@ -33,10 +34,26 @@ export default async function (
...
+            try {
+                contents = (
+                    await octokit.rest.repos.getContent({
+                        ...github.context.repo,
+                        path: filename,
+                        mediaType: { format: "raw" },
+                    })
+                ).data as unknown as string;
+            } catch (e) {
+                if (!(e instanceof Object && "status" in e && e.status === 404))
```
Comment (SamWilsn) [inline src/rules/assets.ts:47]: Does something like this work?

```suggestion
                if (e?.status !== 404)
```

**Review by SamWilsn — COMMENTED** [review]
Otherwise I think this looks good!

File: src/rules/assets.ts (hunk 1 above)
Comment (dionysuzx) [reply src/rules/assets.ts:47]: this looks a lot cleaner but unfortunately it won't compile because:
```
error TS2339: Property 'status' does not exist on type '{}'
```
the problem is `e` isn't typed so we have to narrow it. we could handle this with `@octokit/request-error`:
```
import { RequestError } from "@octokit/request-error";

// ...

} catch (e) {
    if (!(e instanceof RequestError && e.status === 404)) throw e;
}
```
happy to do this if you prefer. i'll need to test the PR e2e again but don't mind doing that.

Comment (SamWilsn) [reply src/rules/assets.ts:47]: Naw, that make sense. I'm happy with this.

**Review by SamWilsn — APPROVED** [review]

**Review by lightclient — APPROVED** [review]
LGTM
